// 这里统一存放action常量

// auth.js
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CREATE_USER_QERUEST = 'CREATE_USER_QERUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
// users.js
export const USERS_QERUEST = 'USERS_QERUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

// queryResource.js
export const QUERY_RESOURCE_QERUEST = 'QUERY_RESOURCE_QERUEST';
export const QUERY_RESOURCE_SUCCESS = 'QUERY_RESOURCE_SUCCESS';
export const QUERY_RESOURCE_FAILURE = 'QUERY_RESOURCE_FAILURE';

// updateAudio.js
export const UPDATE_AUDIO_QERUEST = 'UPDATE_AUDIO_QERUEST';
export const UPDATE_AUDIO_SUCCESS = 'UPDATE_AUDIO_SUCCESS';
export const UPDATE_AUDIO_FAILURE = 'UPDATE_AUDIO_FAILURE';

// updateVideo.js
export const UPDATE_VIDEO_QERUEST = 'UPDATE_VIDEO_QERUEST';
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_FAILURE = 'UPDATE_VIDEO_FAILURE';

// updateImage.js
export const UPDATE_IMG_QERUEST = 'UPDATE_IMG_QERUEST';
export const UPDATE_IMG_SUCCESS = 'UPDATE_IMG_SUCCESS';
export const UPDATE_IMG_FAILURE = 'UPDATE_IMG_FAILURE';

//roles
export const ROLE_REQUEST = 'ROLE_REQUEST';
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS';
export const ROLE_LIST_FAIL = 'ROLE_LIST_FAIL';
export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAIL = 'CREATE_ROLE_FAIL';

//user-roles
export const USER_ROLE_REQUEST = 'USER_ROLE_REQUEST';
export const USER_ROLE_AUTH_SUCC = 'USER_ROLE_AUTH_SUCC';
export const USER_ROLE_AUTH_FAIL = 'USER_ROLE_AUTH_FAIL';
