// 这里统一存放action常量

// auth.js
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';

// users.js
export const USERS_QERUEST = 'USERS_QERUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

// queryResource.js
export const QUERY_RESOURCE_QERUEST = 'QUERY_RESOURCE_QERUEST';
export const QUERY_RESOURCE_SUCCESS = 'QUERY_RESOURCE_SUCCESS';
export const QUERY_RESOURCE_FAILURE = 'QUERY_RESOURCE_FAILURE';

// queryResource.js
export const QUERY_REVIEW_QERUEST = 'QUERY_REVIEW_QERUEST';
export const QUERY_REVIEW_SUCCESS = 'QUERY_REVIEW_SUCCESS';
export const QUERY_REVIEW_FAILURE = 'QUERY_REVIEW_FAILURE';

// review.js
export const REVIEW_QERUEST = 'REVIEW_QERUEST';
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS';
export const REVIEW_FAILURE = 'REVIEW_FAILURE';

// updateAudio.js
export const UPDATE_AUDIO_QERUEST = 'UPDATE_AUDIO_QERUEST';
export const UPDATE_AUDIO_SUCCESS = 'UPDATE_AUDIO_SUCCESS';
export const UPDATE_AUDIO_FAILURE = 'UPDATE_AUDIO_FAILURE';

// getAudio.js
export const GET_AUDIO_QERUEST = 'GET_AUDIO_QERUEST';
export const GET_AUDIO_SUCCESS = 'GET_AUDIO_SUCCESS';
export const GET_AUDIO_FAILURE = 'GET_AUDIO_FAILURE';

// getAudio.js
export const GET_VIDEO_QERUEST = 'GET_VIDEO_QERUEST';
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';
export const GET_VIDEO_FAILURE = 'GET_VIDEO_FAILURE';

// getImage.js
export const GET_IMAGE_QERUEST = 'GET_IMAGE_QERUEST';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAILURE = 'GET_IMAGE_FAILURE';

// updateVideo.js
export const UPDATE_VIDEO_QERUEST = 'UPDATE_VIDEO_QERUEST';
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_FAILURE = 'UPDATE_VIDEO_FAILURE';

// updateImage.js
export const UPDATE_IMG_QERUEST = 'UPDATE_IMG_QERUEST';
export const UPDATE_IMG_SUCCESS = 'UPDATE_IMG_SUCCESS';
export const UPDATE_IMG_FAILURE = 'UPDATE_IMG_FAILURE';

// categorys.js
export const QUERY_CATEGORY_QERUEST = 'QUERY_CATEGORY_QERUEST';
export const QUERY_CATEGORY_SUCCESS = 'QUERY_CATEGORY_SUCCESS';
export const QUERY_CATEGORY_FAILURE = 'QUERY_CATEGORY_FAILURE';
export const CREATE_CATEGORY_QERUEST = 'CREATE_CATEGORY_QERUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';
